### ISSUE TITLE
typo in order.yml—how is this still working?

### ISSUE THREAD

**Issue by t4k** [stefanbuck/ristorante#87]
https://github.com/stefanbuck/ristorante/blob/f068c5ba7e58488e726946c98736969ebeaab972/.github/workflows/order.yml#L16

'praser' instead of 'parser'

**Comment by stefanbuck** [comment]
It is working because I fixed/renqmed the repo. This "feature" is also known as Typosquatting. GitHub redirects https://github.com/stefanbuck/github-issue-praser to https://github.com/stefanbuck/github-issue-parser
